
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://200.152.54.164:90/wservice.asmx?wsdl")
public class WService
    extends Service
{

    private final static URL WSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSERVICE_EXCEPTION;
    private final static QName WSERVICE_QNAME = new QName("http://tempuri.org/", "WService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://200.152.54.164:90/wservice.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSERVICE_WSDL_LOCATION = url;
        WSERVICE_EXCEPTION = e;
    }

    public WService() {
        super(__getWsdlLocation(), WSERVICE_QNAME);
    }

    public WService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSERVICE_QNAME, features);
    }

    public WService(URL wsdlLocation) {
        super(wsdlLocation, WSERVICE_QNAME);
    }

    public WService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSERVICE_QNAME, features);
    }

    public WService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WServiceSoap
     */
    @WebEndpoint(name = "WServiceSoap")
    public WServiceSoap getWServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "WServiceSoap"), WServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WServiceSoap
     */
    @WebEndpoint(name = "WServiceSoap")
    public WServiceSoap getWServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WServiceSoap"), WServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSERVICE_EXCEPTION!= null) {
            throw WSERVICE_EXCEPTION;
        }
        return WSERVICE_WSDL_LOCATION;
    }

}
