
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WServiceSoap {


    /**
     * 
     * @param senha
     * @param idConfig
     * @param usuario
     * @return
     *     returns org.tempuri.ArrayOfWSCliente
     */
    @WebMethod(operationName = "ListaClientesPorUsuario", action = "http://tempuri.org/ListaClientesPorUsuario")
    @WebResult(name = "ListaClientesPorUsuarioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ListaClientesPorUsuario", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListaClientesPorUsuario")
    @ResponseWrapper(localName = "ListaClientesPorUsuarioResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListaClientesPorUsuarioResponse")
    public ArrayOfWSCliente listaClientesPorUsuario(
        @WebParam(name = "Id_Config", targetNamespace = "http://tempuri.org/")
        int idConfig,
        @WebParam(name = "Usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://tempuri.org/")
        String senha);

    /**
     * 
     * @param cliente
     * @param idConfig
     * @return
     *     returns org.tempuri.ArrayOfWSLinha
     */
    @WebMethod(operationName = "ListaLinhasCliente", action = "http://tempuri.org/ListaLinhasCliente")
    @WebResult(name = "ListaLinhasClienteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ListaLinhasCliente", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListaLinhasCliente")
    @ResponseWrapper(localName = "ListaLinhasClienteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListaLinhasClienteResponse")
    public ArrayOfWSLinha listaLinhasCliente(
        @WebParam(name = "Id_Config", targetNamespace = "http://tempuri.org/")
        int idConfig,
        @WebParam(name = "Cliente", targetNamespace = "http://tempuri.org/")
        short cliente);

    /**
     * 
     * @param idConfig
     * @param linha
     * @return
     *     returns org.tempuri.ArrayOfWSRota
     */
    @WebMethod(operationName = "ListaRotasLinha", action = "http://tempuri.org/ListaRotasLinha")
    @WebResult(name = "ListaRotasLinhaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ListaRotasLinha", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListaRotasLinha")
    @ResponseWrapper(localName = "ListaRotasLinhaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListaRotasLinhaResponse")
    public ArrayOfWSRota listaRotasLinha(
        @WebParam(name = "Id_Config", targetNamespace = "http://tempuri.org/")
        int idConfig,
        @WebParam(name = "Linha", targetNamespace = "http://tempuri.org/")
        short linha);

    /**
     * 
     * @param idConfig
     * @param rota
     * @return
     *     returns org.tempuri.ArrayOfWSPontoReferencia
     */
    @WebMethod(operationName = "ListaPontosReferenciaRota", action = "http://tempuri.org/ListaPontosReferenciaRota")
    @WebResult(name = "ListaPontosReferenciaRotaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ListaPontosReferenciaRota", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListaPontosReferenciaRota")
    @ResponseWrapper(localName = "ListaPontosReferenciaRotaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListaPontosReferenciaRotaResponse")
    public ArrayOfWSPontoReferencia listaPontosReferenciaRota(
        @WebParam(name = "Id_Config", targetNamespace = "http://tempuri.org/")
        int idConfig,
        @WebParam(name = "Rota", targetNamespace = "http://tempuri.org/")
        short rota);

    /**
     * 
     * @param cliente
     * @param idConfig
     * @return
     *     returns org.tempuri.ArrayOfWSTrajeto
     */
    @WebMethod(operationName = "ListaTrajetosCliente", action = "http://tempuri.org/ListaTrajetosCliente")
    @WebResult(name = "ListaTrajetosClienteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ListaTrajetosCliente", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListaTrajetosCliente")
    @ResponseWrapper(localName = "ListaTrajetosClienteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListaTrajetosClienteResponse")
    public ArrayOfWSTrajeto listaTrajetosCliente(
        @WebParam(name = "Id_Config", targetNamespace = "http://tempuri.org/")
        int idConfig,
        @WebParam(name = "Cliente", targetNamespace = "http://tempuri.org/")
        short cliente);

    /**
     * 
     * @param idConfig
     * @param latitude
     * @param longitude
     * @return
     *     returns org.tempuri.ArrayOfWSVeiculo
     */
    @WebMethod(operationName = "ListaVeiculosProximos", action = "http://tempuri.org/ListaVeiculosProximos")
    @WebResult(name = "ListaVeiculosProximosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ListaVeiculosProximos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListaVeiculosProximos")
    @ResponseWrapper(localName = "ListaVeiculosProximosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListaVeiculosProximosResponse")
    public ArrayOfWSVeiculo listaVeiculosProximos(
        @WebParam(name = "Id_Config", targetNamespace = "http://tempuri.org/")
        int idConfig,
        @WebParam(name = "Latitude", targetNamespace = "http://tempuri.org/")
        double latitude,
        @WebParam(name = "Longitude", targetNamespace = "http://tempuri.org/")
        double longitude);

    /**
     * 
     * @param idRota
     * @param idConfig
     * @param quantidadePontos
     * @param quantidadeVeiculos
     * @param hashCode
     * @param latitude
     * @param idLinha
     * @param longitude
     * @return
     *     returns org.tempuri.ArrayOfWSVeiculosTrajeto
     */
    @WebMethod(operationName = "ListaVeiculosTrajeto", action = "http://tempuri.org/ListaVeiculosTrajeto")
    @WebResult(name = "ListaVeiculosTrajetoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ListaVeiculosTrajeto", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListaVeiculosTrajeto")
    @ResponseWrapper(localName = "ListaVeiculosTrajetoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ListaVeiculosTrajetoResponse")
    public ArrayOfWSVeiculosTrajeto listaVeiculosTrajeto(
        @WebParam(name = "Id_Config", targetNamespace = "http://tempuri.org/")
        int idConfig,
        @WebParam(name = "Id_Linha", targetNamespace = "http://tempuri.org/")
        short idLinha,
        @WebParam(name = "Id_Rota", targetNamespace = "http://tempuri.org/")
        short idRota,
        @WebParam(name = "Latitude", targetNamespace = "http://tempuri.org/")
        double latitude,
        @WebParam(name = "Longitude", targetNamespace = "http://tempuri.org/")
        double longitude,
        @WebParam(name = "QuantidadeVeiculos", targetNamespace = "http://tempuri.org/")
        short quantidadeVeiculos,
        @WebParam(name = "QuantidadePontos", targetNamespace = "http://tempuri.org/")
        short quantidadePontos,
        @WebParam(name = "HashCode", targetNamespace = "http://tempuri.org/")
        String hashCode);

}
